// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQkIkvFO9sM1gZzDHWmcvBb6i6A4Ano8',
    appId: '1:821115884271:web:6acddc9881b0186a89411a',
    messagingSenderId: '821115884271',
    projectId: 'mapbidan',
    authDomain: 'mapbidan.firebaseapp.com',
    storageBucket: 'mapbidan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfYwCugbhGU3rLa13bFhK8WmAHi-nKCMo',
    appId: '1:821115884271:android:67d198ac947b56d589411a',
    messagingSenderId: '821115884271',
    projectId: 'mapbidan',
    storageBucket: 'mapbidan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfz4oMFMkfy6GNs2GbUyMn4IqlqzOvMlo',
    appId: '1:821115884271:ios:fa6f59b1576c1c1189411a',
    messagingSenderId: '821115884271',
    projectId: 'mapbidan',
    storageBucket: 'mapbidan.appspot.com',
    iosClientId: '821115884271-vjm0nublnu2m4ult46rjsigviils1sr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfz4oMFMkfy6GNs2GbUyMn4IqlqzOvMlo',
    appId: '1:821115884271:ios:fa6f59b1576c1c1189411a',
    messagingSenderId: '821115884271',
    projectId: 'mapbidan',
    storageBucket: 'mapbidan.appspot.com',
    iosClientId: '821115884271-vjm0nublnu2m4ult46rjsigviils1sr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapFlutter',
  );
}
